// AUTO-GENERATED by scripts/blog-ingest.mjs — do not edit by hand.
// Source drafts: content/blog-drafts/*.json. Run `npm run blog:ingest` to regenerate.
import type { BlogPost } from "./blog-types";

export const GENERATED_POSTS: BlogPost[] = [];
